log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://orchestrator:orchestrator@localhost:5432/orchestrator?sslmode=disable"

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: orchestrator
  service_port: 80
