log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://orchestrator:orchestrator@localhost:5432/orchestrator?sslmode=disable"

publisher:
  amqp_url: "amqp://guest:guest@localhost:5672/"

amqp:
  auth: "auth"
  orchestrator: "orchestrator"

subscriber:
  orchestrator: "orchestrator"
  amqp_url: "amqp://guest:guest@localhost:5672/"

listener:
  addr: :8000

jwt:
  secret: SuPeR SeCrEt PhRaSe
  refresh_life: 6h
  access_life: 10m5s

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: orchestrator
  service_port: 80
